import { DetectedEntity, ENTITY_CONFIG, EntityCategory } from './entity-types';

export function generateRedactionReport(
  entities: DetectedEntity[],
  fileName?: string,
): string {
  const accepted = entities.filter((e) => e.accepted);
  const rejected = entities.filter((e) => !e.accepted);

  // Count by category
  const byCat = new Map<EntityCategory, { found: number; redacted: number }>();
  for (const e of entities) {
    const entry = byCat.get(e.category) || { found: 0, redacted: 0 };
    entry.found++;
    if (e.accepted) entry.redacted++;
    byCat.set(e.category, entry);
  }

  // Count by source
  const regexCount = accepted.filter((e) => e.source === 'regex').length;
  const llmCount = accepted.filter((e) => e.source === 'ner').length;

  // Unique redacted texts
  const uniqueRedacted = new Map<string, { text: string; category: EntityCategory; count: number }>();
  for (const e of accepted) {
    const key = `${e.category}:${e.text.toLowerCase().trim()}`;
    const existing = uniqueRedacted.get(key);
    if (existing) {
      existing.count++;
    } else {
      uniqueRedacted.set(key, { text: e.text, category: e.category, count: 1 });
    }
  }

  const lines: string[] = [];
  lines.push('REDACTION REPORT');
  lines.push('================');
  lines.push('Generated by LocalRedact (100% client-side, zero data uploaded)');
  lines.push('');
  if (fileName) lines.push(`Source: ${fileName}`);
  lines.push(`Date: ${new Date().toISOString().slice(0, 19).replace('T', ' ')} UTC`);
  lines.push('');

  lines.push('SUMMARY');
  lines.push('-------');
  lines.push(`Total entities found:    ${entities.length}`);
  lines.push(`Entities redacted:       ${accepted.length}`);
  lines.push(`Entities kept (skipped): ${rejected.length}`);
  lines.push(`Detection: regex=${regexCount}, AI model=${llmCount}`);
  lines.push('');

  lines.push('BY CATEGORY');
  lines.push('-----------');
  for (const [cat, counts] of byCat) {
    const config = ENTITY_CONFIG[cat];
    const label = config?.label || cat;
    lines.push(`${label.padEnd(16)} found: ${String(counts.found).padStart(3)}   redacted: ${String(counts.redacted).padStart(3)}`);
  }
  lines.push('');

  lines.push('REDACTED ITEMS');
  lines.push('--------------');
  // Group by category
  const catOrder = [...byCat.keys()];
  for (const cat of catOrder) {
    const config = ENTITY_CONFIG[cat];
    const label = config?.label || cat;
    const items = [...uniqueRedacted.values()].filter((i) => i.category === cat);
    if (items.length === 0) continue;
    lines.push(`[${label}]`);
    for (const item of items) {
      const suffix = item.count > 1 ? ` (x${item.count})` : '';
      lines.push(`  - ${item.text}${suffix}`);
    }
  }
  lines.push('');

  if (rejected.length > 0) {
    lines.push('KEPT (NOT REDACTED)');
    lines.push('-------------------');
    const uniqueKept = new Map<string, { text: string; category: EntityCategory }>();
    for (const e of rejected) {
      const key = `${e.category}:${e.text.toLowerCase().trim()}`;
      if (!uniqueKept.has(key)) {
        uniqueKept.set(key, { text: e.text, category: e.category });
      }
    }
    for (const item of uniqueKept.values()) {
      const config = ENTITY_CONFIG[item.category];
      lines.push(`  - [${config?.label || item.category}] ${item.text}`);
    }
    lines.push('');
  }

  lines.push('--- End of Report ---');
  return lines.join('\n');
}
